### ISSUE TITLE
State estimator is not working on DC state estimation

### ISSUE THREAD

**Issue by fhdummy** [MATPOWER/matpower-extras#1]
The following error appears, when trying to do a DC state estimation:

```
>> runse('case30', mpoption('model','DC'))
Undefined function or variable 'V'.

Error in runse (line 123)
Sbuslf = V .* conj(Ybus * V);
```

It appears, that the variable `V` only gets assigned, when doing AC state estimation. Additionally, no `Ybus, Yt, Yf` is defined, when running the script `runse.m` with the option `mpoption('model','DC')`. 

Thus, the function `state_est.m` can't be called correctly, because most of the variables are not defined.

Is it planned, that DC state estimation gets implemented soon? Thanks.

**Comment by rdzman** [comment]
The state estimation code is unsupported code, contributed by users like yourself. As you discovered, the existing code is for AC state estimation only. I have no plans to implement DC state estimation, but would be happy to consider including contributed code to implement that feature.
